### ISSUE TITLE
MX2 (and MX1?) chipKIT boards fail simple EEPROM test sketch

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT32-MAX#421]
Something is hozing up EEPROM emulation on the MX2 boards (tested on DP32, Fubarino Mini and chipKIT Pi) and likely on MX1 as well (but I don't have one of those to test).

Here is the test sketch:

```C
#include <EEPROM.h>

void setup() {       
  unsigned int addr = 0;
  unsigned char val = 0;
  unsigned int count = 0;
  bool done = false;
  Serial.begin(115200);

  delay(5000);
  EEPROM.clear();

  while (!done) {
    Serial.print(" Count = ");
    Serial.println(count);  
    // Write new conents in  
    val = EEPROM.read(511) + 10;  // Some value to make a change
    for (addr=0; addr < 512; addr++) {
      EEPROM.write(addr, val);
      if (EEPROM.read(addr) != val) {
        Serial.print("Verify error at address ");
        Serial.print(addr, DEC);
        Serial.print(" wrote ");
        Serial.print(val, DEC);
        Serial.print(" read ");
        Serial.println(EEPROM.read(addr), DEC);
        done = true;
      }
      val = val - 1;
    }
    count++;
  }
  
  // Read through again and print out the new contents
  Serial.println("Reading all values:");
  for (addr=0; addr < 512; addr++) {
    Serial.print("Address: ");
    Serial.print(addr, DEC);
    Serial.print(" Data: ");
    Serial.println(EEPROM.read(addr), DEC);
  }
}

void loop()
{
}
```

When it fails, the output looks like this:

 Count = 0
 Count = 1
 Count = 2
Verify error at address 32 wrote 255 read 244
Verify error at address 256 wrote 31 read 255
Verify error at address 257 wrote 30 read 255
Verify error at address 258 wrote 29 read 255
etc.

If you test this on any other boards (UNO32, Fubarino SD, etc.) the test passes, and just produces the following output:

 Count = 0
 Count = 1
 Count = 2
 Count = 3
 Count = 4
 Count = 5
etc.

I don't know exactly what's going on here, but it always happens the third time through the main loop. Also, it's _critical_ that you start with a 'clean' system before you run the test. This means that either a) you've never run the test before on a board, or b) you just re-programmed the bootloader (and thus just did a complete chip erase).

The reason this is critical is because once the baaaad stuff happens and it starts generating errors, your flash is hozed, and the next time you try to upload a sketch you will get verify errors during the upload process. Not quite sure how that works, or why. 

*Brian

**Comment by ricklon** [comment]
Confirmed fixed.
