### ISSUE TITLE
Make it easier to port Arduino code

### ISSUE THREAD

**Issue by JacobChrist** [chipKIT32/chipKIT32-MAX#451]
1. Define for PIC's, they can be empty or include the defines below.

#include <avr/io.h>
#include <avr/pgmspace.h>

2. Define PROGMEM and nothing...

#define PROGMEM

3. Define memcpy_P as memcpy

#define memcpy_P  memcpy

If these changes had been in place I suspect that the Sha library I ported recently would have just worked out of the box.

Jacob

**Comment by ricklon** [comment]
Confirmed fixed.
