### ISSUE TITLE
Sketches with #include "EEPROM.h" crash on latest MPIDE in GitHub

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT32-MAX#452]
Something, which I haven't been able to track down yet, is causing any sketch that even just does an #include "EEPROM.h" to fail to run when uploaded to a board. (Even the blink sketch, with that include, just does nothing.)

Previous versions didn't have this problem. I'm not sure what commit caused this issue, but it likely has to do with linker scripts, as the EEPROM library depends on stuff there. Just a guess.

**Comment by ricklon** [comment]
confirmed fixed.
