### ISSUE TITLE
Add files needed to create chipKIT-core

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT32-MAX#560]
Add files needed to create chipKIT-core. This would be the platform.txt file, and the pic32prog uploader. Then a complete boards.txt file. Currently, boards.txt is split into the variant subdirectory. Need to make one for drop in portion of Arduino 1.6.x.

**Comment by EmbeddedMan** [comment]
Rick, it feels to me like this is done - since we have a buildable core now that does compile and upload (to some boards). Do you concur or is there more you want to do on this issue?

**Comment by ricklon** [comment]
This is resolved.
