### ISSUE TITLE
SS, MOSI, MISO and SCK defined incorrect in Boards_Defs.h for Fubarino SD

### ISSUE THREAD

**Issue by JacobChrist** [chipKIT32/chipKIT32-MAX#563]
SPIClass::begin() in SPI.cpp in hardware/pic32/libraries

The following code exists:

	pinMode(SS, OUTPUT);

	digitalWrite(SS, HIGH);

Boards_Defs.h for the Fubarino SD has the following defined:

/// TODO: For Fubarino, do we need these?

const static uint8_t SS   = 105;		// PIC32 SS2

const static uint8_t MOSI =	104;		// PIC32 SDO2

const static uint8_t MISO = 103;		// PIC32 SDI2

const static uint8_t SCK  = 102;		// PIC32 SCK2

The Fubarino SD Boards_Def.cpp file only defines 44 pins.  This means that the pinMode and digitalWrite trying to manipulate SS is doing so for a pin that is not defined.  Also the MOSI, MISO and SCK defs are incorrect.

**Comment by EmbeddedMan** [comment]
I have verified that this issue is now fixed. See test code here : https://github.com/fubarino/fubarino.github.com/wiki/Code-Examples
