### ISSUE TITLE
Create a pure 0023 build

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT32-MAX#574]
Create a pure 0023 build. Remove changes from print from commit a18e74707b3c01834b29b45edd2997c0ca68d16f
Then rebase.

**Comment by ricklon** [comment]
Branch "fixprint" was created to hold the 0023 version. I'll have to create a better branch name.

**Comment by ricklon** [comment]
The branch name is now b0023

**Comment by EmbeddedMan** [comment]
Rick is this 0023 build now complete? (since we've done builds of the b0023 branch for all OSes and uploaded them)

**Comment by ricklon** [comment]
This is completed and now posted.
